name: 'tweet_text'
version: '1.0.0'
config-version: 2

profile: 'default'

analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  tweet_text:
    materialized: table
  tickers_from_tweets:
    materialized: table

seeds:
  tweet_text:
    # Config applied to all seed files
    quote_columns: false

